first_x = int(input("Enter first x coordinate: "))
first_y = int(input("Enter first y coordinate: "))
second_x = int(input("Enter second x coordinate: "))
second_y = int(input("Enter second y coordinate: "))

from turtle import *
pendown()
goto(200,0)
pendown()
goto(-200,0)
penup()
goto(0,200)
pendown()
goto(0,-200)
penup()
goto(first_x, first_y)
pendown()
circle(5)
goto(second_x, second_y)
circle(5)
